name: Generate and Send Draft (Daily @13:30 IST)

on:
  schedule:
    - cron: '0 8 * * *'  # 13:30 IST = 08:00 UTC (cron uses UTC)
  workflow_dispatch:

permissions:
  contents: read

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install requests
      - name: Generate draft
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_MODEL: ${{ secrets.HF_MODEL }}
        run: |
          python post_generator.py
          cat draft_post.json
      - name: Send draft to WhatsApp
        env:
          WHATSAPP_TOKEN: ${{ secrets.WHATSAPP_TOKEN }}
          WHATSAPP_PHONE_ID: ${{ secrets.WHATSAPP_PHONE_ID }}
          WHATSAPP_TO_NUMBER: ${{ secrets.WHATSAPP_TO_NUMBER }}
        run: |
          python send_whatsapp.py
      - name: Upload draft artifact
        uses: actions/upload-artifact@v4
        with:
          name: draft
          path: draft_post.json
