name: LinkedIn Auto Poster

on:
  schedule:
    # Runs at 11:00 AM UTC daily (adjust timezone as needed)
    # For 11 AM IST (India), use: '30 5 * * *' (5:30 AM UTC = 11:00 AM IST)
    - cron: '30 5 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  post-to-linkedin:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PAT }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install requests google-generativeai
    
    - name: Run LinkedIn poster
      env:
        LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
        LINKEDIN_PERSON_URN: ${{ secrets.LINKEDIN_PERSON_URN }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        python linkedin_auto_poster.py
    
    - name: Commit post history
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add posts.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Add post record: $(date +'%Y-%m-%d %H:%M:%S')"
        git push
